# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        files: '(.*)\.py'
    -   id: end-of-file-fixer
        files: '(.*)\.py'
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
    -   id: name-tests-test
    -   id: requirements-txt-fixer



-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        additional_dependencies: [types-PyYAML==6.0.1]


-   repo: https://github.com/PyCQA/pylint.git
    rev: v2.16.0
    hooks:
    -   id: pylint
        args: [--max-line-length=110]

